version: '3.8'
services:
  api:
    build:
      context: .
    ports:
      - 6868:6868
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:tuan1234@db:5432/myrestaurant?schema=public
      AT_SECRET: at-secret
      RT_SECRET: rt-secret
  db:
    restart: always
    image: postgres:12
    volumes:
      - ./database:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tuan1234
      POSTGRES_DB: myrestaurant
