version: '3'
services:
  db:
    container_name: postgres
    restart: always
    image: postgres:12
    volumes:
      - ./database:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tuan1234
      POSTGRES_DB: myrestaurant
