version: '3.8'
services:
  api:
    container_name: api
    build:
      context: .
    ports:
      - 6868:6868
  db:
    container_name: postgres
    restart: always
    image: postgres:12
    volumes:
      - ./database:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tuan1234
      POSTGRES_DB: myrestaurant
